name: Python CI

# Adicione o gatilho para acionar o workflow
on:                                # <--- Adicione esta linha
  push:                            # <--- Aciona em qualquer push
    branches: [ main, dev ]        # <--- Aciona em pushes para `main` e `dev`
  pull_request:                    # <--- Aciona em qualquer pull request
    branches: [ main, dev ]        # <--- Aciona PRs para `main` e `dev`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run Tests
        run: poetry run pytest
